/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-16 07:25:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- 메인화면 -->\r\n");
      out.write("<html>\r\n");
      out.write("  <head lang=\"ko\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>SSAFIT</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/Backend_pjt/board/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/Backend_pjt/board/bootstrap/css/bootstrap.css\">\r\n");
      out.write("    <!-- google icon-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- 헤더 -->\r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"page-top\">\r\n");
      out.write("        <span id=\"title\">SSaFit&#128170;</span>\r\n");
      out.write("        <span>\r\n");
      out.write("          <a href=\"/Backend_pjt/board?act=main\" class=\"material-symbols-outlined\">HOME</a>\r\n");
      out.write("          <!-- <a href=\"join.html\" class=\"material-symbols-outlined\">PERSON_ADD</a> -->\r\n");
      out.write("          <a href=\"/Backend_pjt/user?act=loginForm\" class=\"material-symbols-outlined\">LOGIN</a>\r\n");
      out.write("          <!-- <a href=\"logout.html\" class=\"material-symbols-outlined\">LOGOUT</a> -->\r\n");
      out.write("        </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"carouselControlsBanner\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("          <div class=\"carousel-item active\" data-bs-interval=\"10000\">\r\n");
      out.write("            <img src=\"/Backend_pjt/img/gym-gd5f9bf962_1280.jpg\" class=\"d-block w-100\" id=\"banner1\">\r\n");
      out.write("            <div class=\"image-name\">health</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\" data-bs-interval=\"10000\">\r\n");
      out.write("            <img src=\"/Backend_pjt/img/dumbbells-gbb01cca30_1280.jpg\" class=\"d-block w-100\" id=\"banner2\">\r\n");
      out.write("            <div class=\"image-name\">diet</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\" data-bs-interval=\"10000\">\r\n");
      out.write("            <img src=\"/Backend_pjt/img/weight-lifting-g6f7c7bf2f_1280.jpg\" class=\"d-block w-100\" id=\"banner3\">\r\n");
      out.write("            <div class=\"image-name\">training</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#carouselControlsBanner\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#carouselControlsBanner\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- 검색창 -->\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"input-group mb-3 search-input\">\r\n");
      out.write("        <span id=\"search-icon\" class=\"input-group-text material-symbols-outlined\">SEARCH</span>\r\n");
      out.write("        <input id=\"keyword\" type=\"text\" class=\"form-control btn btn-light\" placeholder=\" 검색할 키워드를 입력해 주세요\">\r\n");
      out.write("        <button type=\"button\" class=\"input-group-text btn btn-outline-dark\" id=\"basic-addon2\">검색</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"carouselControlsresearch\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <h3 id=\"search-title\"></h3>\r\n");
      out.write("        <div class=\"carousel-inner row row-cols-1\" id=\"search-cards\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <script src=\"/Backend_pjt/board/search.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 최근 가장 많이 본 영상 -->\r\n");
      out.write("    <section class=\"recent\" id=\"multiple-items\">\r\n");
      out.write("      <h3>&#127916;최근 가장 많이 본 영상</h3>\r\n");
      out.write("      <div id=\"carouselExampleControls2\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\" id=\"recent-card\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#carouselExampleControls2\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#carouselExampleControls2\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <script src=\"/Backend_pjt/board/recent.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 운동 부위 선택 -->\r\n");
      out.write("    <section class=\"select-part\">\r\n");
      out.write("      <h3>&#128194;신체 부위별 운동 영상</h3>\r\n");
      out.write("      <div id=\"buttons\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-dark checked\" id=\"all\"  onclick=\"select_func(this.id)\">전신</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-dark unchecked\" id=\"top\" onclick=\"select_func(this.id)\">상체</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-dark unchecked\" id=\"bottom\" onclick=\"select_func(this.id)\">하체</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-dark unchecked\" id=\"stomach\" onclick=\"select_func(this.id)\">복부</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"carouselExampleControls3\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\" id=\"select-cards\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#carouselExampleControls3\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#carouselExampleControls3\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"select_part\"></div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <script src=\"/Backend_pjt/board/select_part.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Backend_pjt/board/bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
